import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JUMP_GOALS,evaluateJumpGoals} from '../src/jumpGoals.js';

const read=path=>fs.readFileSync(new URL('../'+path,import.meta.url),'utf8');
const main=read('src/main.js'),game=read('src/game.js'),runtime=read('src/runtimeEnhancements.js'),results=read('src/results.js'),physics=read('src/physics.js'),director=read('src/jumpGameplayDirector.js'),scenery=read('src/scenery.js'),audio=read('src/audio.js'),character=read('src/character.js'),mobileBudget=read('src/mobileVisualBudget.js'),quality=read('src/jumpRenderQuality.js'),input=read('src/InputManager.js'),leaderboard=read('src/leaderboard.js'),mastery=read('src/jumpMasteryPresentation.js'),trace=read('src/runtime/InputTrace.js'),replay=read('server/lib/replay.mjs');

assert(main.includes("'test'"),'test mode must route to Chimp Jump, not the launcher');
assert(!mobileBudget.includes('Object3D.prototype.add'),'mobile visual budgets must never patch THREE.Object3D.prototype.add');
assert(!main.includes("import('./mobileVisualBudget.js')"),'mobile visual budget must not be loaded for side effects');
for(const tier of ["'balanced'","'high'","'ultra'"])assert(quality.includes(tier),'quality architecture must retain '+tier);
assert(!quality.includes("from './physics")&&!quality.includes("from './InputManager")&&!quality.includes("from './leaderboard"),'quality module must not import gameplay/input/leaderboard systems');
assert(!physics.includes('jumpRenderQuality')&&!input.includes('jumpRenderQuality')&&!leaderboard.includes('jumpRenderQuality'),'visual quality must never affect physics, input or leaderboard rules');
assert(main.includes("setupJumpExperience"),'the framework experience layer must mount');
assert(main.includes('setupJumpMasteryPresentation'),'the mastery presentation layer must mount');
assert(!runtime.includes('new KeyboardEvent'),'mouse steering must never synthesize keyboard key-up/down events');
assert(!runtime.includes('columns=3'),'desktop character navigation must not hardcode the old three-column grid');
assert(game.includes('countdownTime=3')&&game.includes('introTime=0'),'fresh runs must begin in the frozen countdown close-up');
assert(game.includes('const startZoom=2.08'),'countdown and intro must keep the requested character close-up');
assert(!game.includes('const startZoom=1.72'),'the old opening zoom must not return');
assert(game.includes("chimp-jump-muted")&&game.includes("chimp-jump-detail"),'player preferences must persist');
assert(!game.includes("entry.id==='steamboat-willie'")&&!game.includes("entry.id==='chimpion'"),'Willie and Silver Chimp must not be special hero-selection defaults');
assert(game.includes("chimp-run-finished"),'completed runs must publish a summary for goals');
assert(results.includes('Replay this trail'),'results must expose reproducible same-seed practice');
for(const type of ["'leaf'","'vanish'","'swing'"])assert(physics.includes(type),'canopy expansion must retain '+type+' platform generation');
assert(!physics.includes("leaf:'moving'")&&!physics.includes("swing:'moving'")&&!physics.includes("vanish:'cracked'"),'leaf, swing and vanish must be real mechanics, not aliases');
assert(physics.includes('landingQuality')&&physics.includes("'PERFECT'")&&physics.includes("'EDGE'"),'landing mastery must be authoritative in physics');
assert(physics.includes('flowMultiplier')&&physics.includes('skillBonus'),'Flow and mastery scoring must be authoritative in physics');
assert(input.includes('isFastFallPressed')&&trace.includes('fastFall')&&replay.includes('fastFall'),'Fast Fall must remain input-traced and server-replayable');
assert(physics.includes('FAST_FALL_EXTRA_GRAVITY=24')&&physics.includes('FAST_FALL_MAX_SPEED=33'),'Fast Fall 50% speed tuning must remain');
assert(mastery.includes('jump-flow-hud')&&!mastery.includes('jump-mastery-feedback')&&!mastery.includes("showFeedback('FAST FALL')"),'Flow HUD must remain wired without center mastery feedback');
assert(mastery.includes('#hud .stat')&&mastery.includes('background:transparent'),'top run HUD must remain transparent');
assert(!physics.includes('windAt')&&physics.includes("'event-start'"),'wind must be absent while timed canopy events remain wired into physics');
for(const type of ["'thorn-pod'","'swinging-pod'","'vine-sweep'","'falling-fruit'"])assert(director.includes(type),'gameplay director must expose hazard '+type);
assert(scenery.includes('animateHazard')&&scenery.includes('jetTrail'),'hazard animation and jet trail polish must remain');
assert(scenery.includes("organic-platform-detail"),'special procedural platforms must retain the organic high-detail contour pass');
assert(scenery.includes('TREE_SCROLL_PER_SCREEN')&&scenery.includes('computeTreeScroll')&&scenery.includes('treeClimbOffset'),'the authored giant tree must retain camera-relative infinite scrolling');
assert(audio.includes('setIntensity')&&audio.includes('milestone'),'reactive music and milestone audio must remain');
assert(game.includes("countdown.id='countdown'")&&game.includes("mode='starting'")&&game.includes('finishCountdown'),'run countdown must remain wired before gameplay');
assert(game.includes('BANANA_HEIGHT+Math.sin'),'banana visuals must remain elevated above branches');
assert(physics.includes('BANANA_HEIGHT=1.35')&&physics.includes('safeBanana')&&physics.includes('addOptional'),'banana height and seeded optional reward distribution must remain');
assert(!scenery.includes('const edgeVines=new THREE.Group'),'screen-edge vine curtain must stay removed');
assert(!scenery.includes('rope=mesh(logGeo,vineGlow,swingRig'),'swing branches must not draw long ropes into the screen border');
for(const stage of ["'TAKEOFF'","'ASCEND'","'APEX'","'DESCEND'","'LAND'"])assert(character.includes(stage),'jump animation must expose '+stage+' staging');

assert.equal(JUMP_GOALS.length,6,'ship six optional expedition goals');
const sample=evaluateJumpGoals({meters:120,bananas:28,cleanLandings:32},[]);
assert.equal(sample.unlocked.length,6,'a qualifying run should unlock all goals');
const repeat=evaluateJumpGoals({meters:120,bananas:28,cleanLandings:32},sample.unlocked);
assert.equal(repeat.newlyUnlocked.length,0,'goals must not announce twice');

assert(physics.includes("2026-10-expedition-v15-mastery"),'replay/server RULESET must reflect mastery gameplay semantic changes');
assert(director.includes('READ')&&director.includes('BUILD')&&director.includes('CHALLENGE')&&director.includes('RELEASE')&&director.includes('REWARD'),'encounter pacing grammar must remain explicit');
console.log('PASS Chimp Jump audit gates: routing, camera, replay, mastery mechanics, clean HUD, Fast Fall tuning, goals, director grammar, hazard vocabulary and RULESET');
