// Reused from CyberArtsBR/chimpions-dash/dist/audio.js (original Chimpions Dash audio).
// User-gesture-only Web Audio. Slide-dash loop is controlled explicitly by actual slide input.
export class GameAudio {
 constructor(enabled=false){this.enabled=enabled;this.context=null;this.failed=false;this.dashActive=false;this.dashOsc=null;this.dashLfo=null;this.dashNoise=null;this.dashGain=null;this.dashNoiseGain=null;this.noiseBuffer=null;this.music=null;this.musicWanted=false;this.musicSrc='assets/chimpions-army.mp3';this.musicVolume=.22}
 ensure(){this.context??=new(window.AudioContext||window.webkitAudioContext)();const c=this.context;if(c.state==='suspended')c.resume().catch(()=>{});return c}
 musicNode(){if(this.music)return this.music;if(typeof window.Audio!=='function')return null;const m=new window.Audio(this.musicSrc);m.loop=true;m.preload='auto';m.volume=this.musicVolume;m.setAttribute?.('playsinline','');this.music=m;return m}
 startMusic(){this.musicWanted=true;if(!this.enabled)return;const m=this.musicNode();if(!m)return;m.volume=this.musicVolume;const p=m.play?.();p?.catch?.(()=>{})}
 suspendMusic(){this.music?.pause?.()}
 resumeMusic(){if(this.musicWanted&&this.enabled)this.startMusic()}
 stopMusic(){this.musicWanted=false;if(this.music){this.music.pause?.();try{this.music.currentTime=0}catch{}}}
 setEnabled(enabled){this.enabled=!!enabled;if(!this.enabled){this.setDash(false);this.suspendMusic()}else if(this.musicWanted)this.resumeMusic()}
 setDash(active){if(!this.enabled||this.failed){if(this.dashActive)this.stopDashLoop();return}try{this.ensure();active=!!active;if(active===this.dashActive)return;this.dashActive=active;if(active)this.startDashLoop();else this.stopDashLoop()}catch{this.failed=true;this.enabled=false;this.stopDashLoop(false)}}
 play(kind){if(!this.enabled||this.failed)return;try{const c=this.ensure();if(kind==='jump'){this.hoot(c.currentTime,300,540,.13);this.hoot(c.currentTime+.13,480,260,.17);return}if(['dash-start','dash-end'].includes(kind))return;if(kind==='chimpion-mode'){this.oneShot(kind);return}if(kind==='dead')this.setDash(false);this.oneShot(kind)}catch{this.failed=true;this.enabled=false}}
 oneShot(kind){const c=this.context,notes={land:110,pass:670,banana:1150,golden:1480,power:890,'shield-used':180,slide:145,stage:760,'chimpion-mode':980,'PERFECT JUMP':920,'PERFECT SLIDE':840,'CLOSE CALL':520,dead:85,record:1040,click:320};let o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type=['banana','golden','record'].includes(kind)?'sine':'triangle';o.frequency.setValueAtTime(notes[kind]||300,c.currentTime);o.frequency.exponentialRampToValueAtTime((notes[kind]||300)*(['banana','golden','stage','chimpion-mode'].includes(kind)?1.45:.55),c.currentTime+.12);g.gain.setValueAtTime(kind==='chimpion-mode'?.045:.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.15);o.start();o.stop(c.currentTime+.16)}
 hoot(t,start,end,length){const c=this.context,o=c.createOscillator(),filter=c.createBiquadFilter(),g=c.createGain();o.type='sawtooth';o.frequency.setValueAtTime(start,t);o.frequency.exponentialRampToValueAtTime(end,t+length*.55);o.frequency.exponentialRampToValueAtTime(start*.8,t+length);filter.type='bandpass';filter.frequency.setValueAtTime(850,t);filter.frequency.exponentialRampToValueAtTime(580,t+length);filter.Q.value=2.5;o.connect(filter);filter.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(.16,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+length);o.start(t);o.stop(t+length+.01)}
 noiseBufferFor(c){if(this.noiseBuffer&&this.noiseBuffer.sampleRate===c.sampleRate)return this.noiseBuffer;const buffer=this.noiseBufferFor(c);this.noiseBuffer=buffer;return buffer}
 startDashLoop(){const c=this.ensure();this.stopDashNodes(false);const osc=c.createOscillator(),lfo=c.createOscillator(),lfoGain=c.createGain(),filter=c.createBiquadFilter(),gain=c.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(88,c.currentTime);lfo.type='sine';lfo.frequency.setValueAtTime(7.2,c.currentTime);lfoGain.gain.setValueAtTime(9,c.currentTime);filter.type='lowpass';filter.frequency.setValueAtTime(620,c.currentTime);filter.Q.value=.75;gain.gain.setValueAtTime(.0001,c.currentTime);gain.gain.linearRampToValueAtTime(.045,c.currentTime+.035);lfo.connect(lfoGain);lfoGain.connect(osc.frequency);osc.connect(filter);filter.connect(gain);gain.connect(c.destination);osc.start();lfo.start();const buffer=c.createBuffer(1,c.sampleRate,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.14;const noise=c.createBufferSource(),noiseFilter=c.createBiquadFilter(),noiseGain=c.createGain();noise.buffer=buffer;noise.loop=true;noiseFilter.type='bandpass';noiseFilter.frequency.setValueAtTime(1200,c.currentTime);noiseFilter.Q.value=.7;noiseGain.gain.setValueAtTime(.0001,c.currentTime);noiseGain.gain.linearRampToValueAtTime(.015,c.currentTime+.035);noise.connect(noiseFilter);noiseFilter.connect(noiseGain);noiseGain.connect(c.destination);noise.start();this.dashOsc=osc;this.dashLfo=lfo;this.dashNoise=noise;this.dashGain=gain;this.dashNoiseGain=noiseGain}
 stopDashNodes(fade=true){const c=this.context;if(!c)return;const now=c.currentTime,tail=fade?.08:.01;try{if(this.dashGain){this.dashGain.gain.cancelScheduledValues(now);this.dashGain.gain.setValueAtTime(Math.max(.0001,this.dashGain.gain.value||.02),now);this.dashGain.gain.exponentialRampToValueAtTime(.0001,now+tail)}}catch{}try{if(this.dashNoiseGain){this.dashNoiseGain.gain.cancelScheduledValues(now);this.dashNoiseGain.gain.setValueAtTime(Math.max(.0001,this.dashNoiseGain.gain.value||.006),now);this.dashNoiseGain.gain.exponentialRampToValueAtTime(.0001,now+tail)}}catch{}try{this.dashOsc?.stop(now+tail+.02)}catch{}try{this.dashLfo?.stop(now+tail+.02)}catch{}try{this.dashNoise?.stop(now+tail+.02)}catch{}this.dashOsc=null;this.dashLfo=null;this.dashNoise=null;this.dashGain=null;this.dashNoiseGain=null}
 stopDashLoop(fade=true){this.dashActive=false;this.stopDashNodes(fade)}
}
