import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Game,STEP,RULESET} from '../../src/physics.js';
import {createLeaderboardService} from '../lib/service.mjs';
import {MemoryRateLimiter} from '../lib/rateLimiter.mjs';
import {MAX_STEPS,MAX_TRACE_SEGMENTS,RUN_TTL_MS} from '../lib/protocol.mjs';
import {validateTrace} from '../lib/replay.mjs';

function deathTrace(seed,axis=1000){const game=new Game(seed);let count=0;while(!game.dead&&count<MAX_STEPS){game.step(axis/1000,STEP);count++;}assert.equal(game.dead,true);return [[axis,count]];}
function longDeathTrace(seed){const game=new Game(seed);let neutral=0;while(!game.dead&&neutral<600){game.step(0,STEP);neutral++;}let exit=0;while(!game.dead&&neutral+exit<MAX_STEPS){game.step(1,STEP);exit++;}assert.equal(game.dead,true);return [[0,neutral],[1000,exit]];}
async function fixture(options={}){
 const dir=mkdtempSync(join(tmpdir(),'chimp-lb-'));let now=1_800_000_000_000;
 const service=createLeaderboardService({dbPath:join(dir,'scores.sqlite'),allowedOrigins:['https://game.example'],clock:()=>now,logger:()=>{},...options});
 await new Promise(resolve=>service.server.listen(0,'127.0.0.1',resolve));const {port}=service.server.address();const base=`http://127.0.0.1:${port}`;
 const request=async(path,{method='GET',body,origin='https://game.example',headers={}}={})=>{
  const response=await fetch(base+path,{method,headers:{...(origin?{Origin:origin}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},body:body!==undefined?(typeof body==='string'?body:JSON.stringify(body)):undefined});
  let data=null;try{data=await response.json();}catch{}return {response,data};
 };
 return {service,dir,request,advance:ms=>{now+=ms;},get now(){return now;},async close(){await new Promise(resolve=>service.server.close(resolve));service.closeResources();rmSync(dir,{recursive:true,force:true});}};
}
async function begin(fx,extra={}){const result=await fx.request('/api/runs',{method:'POST',body:{rulesetVersion:RULESET,protocolVersion:1,traceVersion:1,...extra}});assert.equal(result.response.status,201);return result.data;}

await test('health and valid deterministic finish are versioned and server-authoritative',async()=>{const fx=await fixture();try{const health=await fx.request('/health');assert.equal(health.response.status,200);assert.equal(health.data.service,'chimp-jump-leaderboard');const ticket=await begin(fx);const trace=deathTrace(ticket.seed);fx.advance(Math.ceil(trace[0][1]*STEP*1000));const finish=await fx.request(`/api/runs/${ticket.id}/finish`,{method:'POST',body:{trace,traceVersion:1,seed:ticket.seed}});assert.equal(finish.response.status,200);assert.ok(Number.isInteger(finish.data.score));assert.equal(finish.data.rulesetVersion,RULESET);}finally{await fx.close();}});

await test('finish retries are idempotent only for the same trace',async()=>{const fx=await fixture();try{const ticket=await begin(fx);const trace=deathTrace(ticket.seed);fx.advance(Math.ceil(trace[0][1]*STEP*1000));const path=`/api/runs/${ticket.id}/finish`;assert.equal((await fx.request(path,{method:'POST',body:{trace}})).response.status,200);assert.equal((await fx.request(path,{method:'POST',body:{trace}})).response.status,200);const altered=[[trace[0][0],trace[0][1]-1],[-1000,1]];const conflict=await fx.request(path,{method:'POST',body:{trace:altered}});assert.equal(conflict.response.status,409);assert.equal(conflict.data.code,'RUN_ALREADY_FINISHED');}finally{await fx.close();}});

await test('timing validation rejects implausibly fast replay',async()=>{const fx=await fixture();try{const ticket=await begin(fx);const trace=longDeathTrace(ticket.seed);const finish=await fx.request(`/api/runs/${ticket.id}/finish`,{method:'POST',body:{trace}});assert.equal(finish.response.status,400);assert.equal(finish.data.code,'TIMING_REJECTED');}finally{await fx.close();}});

await test('expired, unknown, wrong-seed and unsupported trace submissions are rejected',async()=>{const fx=await fixture();try{const unknown='a'.repeat(48);assert.equal((await fx.request(`/api/runs/${unknown}/finish`,{method:'POST',body:{trace:[]}})).data.code,'RUN_NOT_FOUND');const expired=await begin(fx);fx.advance(RUN_TTL_MS+1);assert.equal((await fx.request(`/api/runs/${expired.id}/finish`,{method:'POST',body:{trace:[]}})).data.code,'RUN_EXPIRED');const ticket=await begin(fx);const trace=deathTrace(ticket.seed);fx.advance(Math.ceil(trace[0][1]*STEP*1000));assert.equal((await fx.request(`/api/runs/${ticket.id}/finish`,{method:'POST',body:{trace,seed:(ticket.seed+1)>>>0}})).data.code,'SEED_MISMATCH');assert.equal((await fx.request(`/api/runs/${ticket.id}/finish`,{method:'POST',body:{trace,traceVersion:999}})).data.code,'UNSUPPORTED_TRACE_VERSION');}finally{await fx.close();}});

await test('trace validation rejects malformed shapes, segment abuse and excessive steps',()=>{for(const trace of [null,{},'x',[[0,0]],[[0,-1]],[[0,1.5]],[[1001,1]],[[-1001,1]],[[0,MAX_STEPS+1]],[[0,1,2]]])assert.throws(()=>validateTrace(trace),error=>error.code==='INVALID_TRACE'||error.code==='TRACE_TOO_MANY_STEPS');assert.throws(()=>validateTrace([[0,MAX_STEPS],[0,1]]),error=>error.code==='TRACE_TOO_MANY_STEPS');assert.throws(()=>validateTrace(Array(MAX_TRACE_SEGMENTS+1).fill([0,1])),error=>error.code==='TRACE_TOO_MANY_SEGMENTS');});

await test('content type, JSON, methods, origins, names and body cap fail cleanly',async()=>{const fx=await fixture();try{const method=await fx.request('/api/leaderboard',{method:'POST',body:{}});assert.equal(method.response.status,405);const origin=await fx.request('/api/leaderboard',{origin:'https://evil.example'});assert.equal(origin.data.code,'ORIGIN_REJECTED');const malformed=await fx.request('/api/runs',{method:'POST',body:'{'});assert.equal(malformed.data.code,'INVALID_JSON');const media=await fx.request('/api/runs',{method:'POST',body:'{}',headers:{'Content-Type':'text/plain'}});assert.equal(media.response.status,415);const big=await fx.request('/api/runs',{method:'POST',body:{rulesetVersion:RULESET,pad:'x'.repeat(1_500_100)}});assert.equal(big.response.status,413);const ticket=await begin(fx);const trace=deathTrace(ticket.seed);fx.advance(Math.ceil(trace[0][1]*STEP*1000));await fx.request(`/api/runs/${ticket.id}/finish`,{method:'POST',body:{trace}});const badName=await fx.request(`/api/runs/${ticket.id}/name`,{method:'POST',body:{name:'<script>'}});assert.equal(badName.data.code,'INVALID_PLAYER_NAME');}finally{await fx.close();}});

await test('per-route rate limit is enforced without storing raw IPs',async()=>{const limiter=new MemoryRateLimiter({runCreate:{limit:1,windowMs:60_000},runFinish:{limit:30,windowMs:60_000},runName:{limit:30,windowMs:60_000},leaderboardRead:{limit:120,windowMs:60_000},recordsRead:{limit:120,windowMs:60_000}});const fx=await fixture({rateLimiter:limiter});try{await begin(fx);const limited=await fx.request('/api/runs',{method:'POST',body:{rulesetVersion:RULESET}});assert.equal(limited.response.status,429);assert.equal(limited.data.code,'RATE_LIMITED');assert.ok([...limiter.buckets.keys()].every(key=>!key.includes('127.0.0.1')));}finally{await fx.close();}});

await test('concurrent run creation produces unique secure tickets',async()=>{const fx=await fixture();try{const responses=await Promise.all(Array.from({length:10},()=>fx.request('/api/runs',{method:'POST',body:{rulesetVersion:RULESET}})));assert.ok(responses.every(item=>item.response.status===201));const ids=responses.map(item=>item.data.id);assert.equal(new Set(ids).size,ids.length);assert.ok(ids.every(id=>/^[a-f0-9]{48}$/.test(id)));}finally{await fx.close();}});

await test('concurrent valid submissions and leaderboard reads remain safe',async()=>{const fx=await fixture();try{const tickets=await Promise.all(Array.from({length:4},()=>begin(fx)));const traces=tickets.map(ticket=>deathTrace(ticket.seed));const maxMs=Math.max(...traces.map(trace=>Math.ceil(trace[0][1]*STEP*1000)));fx.advance(maxMs);const finishes=await Promise.all(tickets.map((ticket,index)=>fx.request(`/api/runs/${ticket.id}/finish`,{method:'POST',body:{trace:traces[index]}})));assert.ok(finishes.every(item=>item.response.status===200));const reads=await Promise.all(Array.from({length:12},()=>fx.request('/api/leaderboard')));assert.ok(reads.every(item=>item.response.status===200));}finally{await fx.close();}});

await test('database ranking uses score desc then finish time then run id, and survives restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'chimp-lb-rank-'));const db=join(dir,'scores.sqlite');let service=createLeaderboardService({dbPath:db,allowedOrigins:['https://game.example'],logger:()=>{}});try{const s=service.store;s.createRun({id:'1'.repeat(48),seed:1,started:1,expires:999999,ruleset:RULESET,protocolVersion:1,traceVersion:1});s.createRun({id:'2'.repeat(48),seed:2,started:1,expires:999999,ruleset:RULESET,protocolVersion:1,traceVersion:1});s.finishRun('2'.repeat(48),20,{meters:10,bananas:0,score:10},'a');s.finishRun('1'.repeat(48),10,{meters:10,bananas:0,score:10},'b');s.setName('2'.repeat(48),'B');s.setName('1'.repeat(48),'A');assert.deepEqual(s.board().map(row=>row.name),['A','B']);service.closeResources();service=null;service=createLeaderboardService({dbPath:db,allowedOrigins:['https://game.example'],logger:()=>{}});assert.deepEqual(service.store.board().map(row=>row.name),['A','B']);}finally{service?.closeResources();rmSync(dir,{recursive:true,force:true});}});
